### ISSUE TITLE
ClassNotFound : IArmorEnderium

### ISSUE THREAD

**Issue by ZaRpX** [Tomson124/SimplyJetpacks2#7] opened 2020-04-14 12:19 UTC
When I place the Flux-infused JetPlate on me, an error occurs on my customer luncher:
at tonius.simplyjetpacks.item.ItemJetpack.chargeInventory(ItemJetpack.java:551)
	at tonius.simplyjetpacks.item.ItemJetpack.onArmorTick(ItemJetpack.java:131)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:371)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:1011)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: thundr.redstonerepository.api.IArmorEnderium
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more

Don't hesitate if you need help, I can help you to solve the problem, I have a good knowledge in Java ;)

**Comment by Tomson124** [comment] 2020-04-15 07:37
Which mods (and which versions of it) do you have installed? Maybe provide the full crashlog as a pastebin link.

**Comment by Tomson124** [comment] 2020-11-03 11:57
Closing this due to missing information

**Closed as completed by Tomson124** 2020-11-03 11:57 UTC
Labels: information, 1.12.x

**Comment by Stapleton** [comment] 2021-02-26 19:20
I hope its not an issue if I revive this. I am getting this issue just recently as well and cannot log into my server due to it.

I was in my AE system grabbing 3 16384k storage cells, using Space+Shift to take out all the stacks (each drive is its own), and then I got kicked with a VanillaFix crash from Simply Jetpacks 2, now I get an "Internal Server Error" every time I try to log in now.

Modpack: FTB Revelation 3.4.0
Extra Mods: Extra Cells 2, Realistic Item Drops, Gliby's Voice Chat
Simply Jetpacks Version: 2.2.13.66

[debug.log](https://gist.github.com/Stapleton/1739b03ce33d2067d21ea14fa9b2b62b), [latest.log](https://gist.github.com/Stapleton/9989322e3ca51b14871ff93884da5656), [client-crash.log](https://gist.github.com/Stapleton/16221337411853e0c853de665bb0edef)

Some of the key errors given
`[net.minecraft.network.NetworkSystem]: Failed to handle packet for /10.0.0.181:48832
net.minecraft.util.ReportedException: Ticking player`

`Caused by: java.lang.NoClassDefFoundError: thundr/redstonerepository/api/IArmorEnderium`

I hope I can provide some of the extra information that OP didnt give.
