### ISSUE TITLE
1.17.1 Server Crash on startup

### ISSUE THREAD

**Issue by TheLoneNeighbour** [Tomson124/SimplyJetpacks2#61] opened 2021-08-17 18:28 UTC
Minecraft: 1.17.1
Forge: 37.0.34
SimplyJetpacks2: 1.17.1-2.7.1.1

There are other mods installed but it only crashes when simply jetpacks 2 is installed.
https://mclo.gs/l7k6Keu

**Comment by tomheaton** [comment] 2021-08-17 19:19
any chance you could give it a try with just Simply Jetpacks 2? Sadly that log contains no useful information what so ever. If there are any other logs you could find and upload, then that would be much appreciated.

**Comment by tomheaton** [comment] 2021-08-17 19:22
Also please keep in mind that Simply Jetpacks 2 is back in beta for 1.17.1, just until any know bugs can be found and new content fully implemented. :)

**Comment by TheLoneNeighbour** [comment] 2021-08-18 12:35
new log with just simply jetpacks 2
https://mclo.gs/J97J8rQ

**Comment by tomheaton** [comment] 2021-08-21 09:45
Duplicate of #58

**Closed as completed** 2021-09-04 10:41 UTC
Labels: bug, duplicate, 1.17.x
